version: '3.3'
services:
  connect:
    image: debezium/connect:1.7
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: redpanda:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect.configs
      OFFSET_STORAGE_TOPIC: connect.offset
      STATUS_STORAGE_TOPIC: connect.status
networks:
  default:
    external: true
    name: test-network
